"""Initial migration

Revision ID: c73305aa19a3
Revises: 
Create Date: 2024-08-09 18:52:50.861681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73305aa19a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addmp',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('medicine', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('addpd',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('medicines', sa.String(length=500), nullable=False),
    sa.Column('products', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mid', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('medicines')
    op.drop_table('logs')
    op.drop_table('addpd')
    op.drop_table('addmp')
    # ### end Alembic commands ###
